# Generated by Django 6.1.1 on 2026-09-15 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='customers',
            field=models.ManyToManyField(to='customer.customer'),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='courses.coursetype'),
        ),
    ]
