# Generated by Django 6.1.1 on 2026-09-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_type_and_customers'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='customers',
            field=models.ManyToManyField(blank=True, to='customer.customer'),
        ),
    ]
